### PR TITLE
Fixes #10: Change icons alpha to 1

### LINKED ISSUE #10: Add check of alpha channel for app icons
I have an error during upload to AppStore Connect:
> [iTMSTransporter] 		ERROR ITMS-90396: "Invalid Icon. The watch application 'Waterbalance.app/Watch/WatchKit.app' contains an icon file 'Icon Image-AppIcon-watch-29x29@3x.png' with an alpha channel. Icons should not have an alpha channel."

I want to add check of alpha channel.

### PR DESCRIPTION
**Pull request by imvm**
Uploading Icons generated from images with transparency in iTunes Connect should now work.

### CODE REVIEW

**Comment by artemnovichkov** [comment]
Hello, @imvm! Thank you for the PR! IS it related to #10? What's about transparent areas in images? Will they be filled with white color?

**Comment by imvm** [comment]
Yep, I'm hoping it will fix #10. I ran sasha on a PNG with transparency and it outputted the appiconset with transparent images as well. With this change, the transparent areas in the generated images are all filled with black color. It probably won't look great, but I think that's also what makeappicon.com does if I'm not mistaken.

**Comment by artemnovichkov** [comment]
What do you think, should we return an error if a user uses an image with transparent areas?

**Comment by imvm** [comment]
I think that might not be a good idea in cases where someone whips up a quick icon for their prototype app and doesn't want to spend time checking or fixing the alpha layer. Maybe there could be a verbose option where the program would print out something like: "Detected transparency areas... removing alpha channel..." just so that the user is aware if their icon turns out differently than is expected.

**Comment by artemnovichkov** [comment]
I agree. This check only required for App Store ready icons. Do you mind to add this warning?

**Comment by imvm** [comment]
I did the check in a roundabout kind of way because I couldn't find an easy way to check for transparent regions in CIImage. So I import AppKit and load a NSImageRep from the imageURL when the image is being loaded to use its .hasAlpha() function which is basically what we want.

**Comment by imvm** [comment]
Also I put in a unicode yellow color to make the warning more visible, I think in the future using a library like https://github.com/onevcat/Rainbow would make it nicer to use visually. Just having something like warnings in yellow, errors in red, and success in green.

**Comment by artemnovichkov** [comment]
Hi, @imvm! Sorry for long time response. I don't like an idea of AppKit using, but I guess it's the best and simplest implementation of alpha check. I'll review all your PRs today.

**Review by artemnovichkov — APPROVED** [review]

**Pull request merged**
